<?php 
/** 
* @file 
* Provide a simulated beep. 
*/ 
function beep_beep() { 
watchdog('beep', 'Beep!'); 
} 
 
function beep_beep_action() { 
beep_beep(); 
} 

function beep_action_info() { 
return array( 
'beep_beep_action' => array( 
'type' => 'system', 
'label' => t('Beep annoyingly'), 
'configurable' => FALSE, 
'triggers' => array('node_view', 'node_insert', 'node_update', 'node_delete'), 
), 
); 
}